FROM rust:1.91.1-slim

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY migration/Cargo.toml ./migration/

COPY src ./src
COPY migration/src ./migration/src

EXPOSE 8080

CMD ["cargo", "watch", "-x", "run --bin rest_app"]
